name: snacky_example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  snacky:
    path: ../
  impaktfull_ui: ^0.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1

dependency_overrides:
  snacky:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - ../assets/icons/
    - ../assets/logo.png
