include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - build/**
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - unawaited_futures  