name: snacky
description: A super simple way to show custom snackbars in Flutter.
version: 0.0.1
homepage: https://github.com/Impaktfull/flutter_snacky
topics:
  - snackbar
  - flutter-snackbar
  - custom-flutter-snackbar
  - flutter-flushbar
  - custom-flutter-toast

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: