name: Publish to github pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read

# Never cancel a deployment that is in progress, but only the latest queued one
# runs.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build_example_web.yml
    with:
      upload-pages-artifact: true

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
