name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: impaktfull/gh_action_dart_conventional_release/.github/workflows/flutter_release.yml@main
    with:
      environment: 'pub.dev'